spring:
  thymeleaf:
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123qwe
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间，默认600000（10分钟）
      idle-timeout: 1800000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（半小时）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 3000
      #测试连接是否可用的语句
      connection-test-query: SELECT 1
  data:
    redis:
      host: 192.168.44.128
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          #最大连接数 默认8
          max-active: 8
          #最大连接阻塞时间
          max-wait: 1000ms
          #最大空闲连接，默认8
          max-idle: 200
  rabbitmq:
    host: 192.168.44.128
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1

#MyBatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.joe.seckilldemo.entity

# MyBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.joe.seckilldemo.mapper: debug